const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const authView=$("#auth-view"),dashboard=$("#dashboard"),loginForm=$("#login-form"),gameForm=$("#game-form"),empty=$("#editor-empty");
let config,games=[],currentSlug="",loadedGame=null,token=sessionStorage.getItem("67codes_admin_token")||"";
const demo=location.hostname==="127.0.0.1"&&new URLSearchParams(location.search).has("demo");
const lines=value=>String(value||"").split(/\n/).map(item=>item.trim()).filter(Boolean);
const codes=value=>[...new Set(String(value||"").split(/[,\n]/).map(item=>item.trim()).filter(Boolean))];
const setMessage=(target,text,type="")=>{target.textContent=text;target.className=`form-message ${type}`};
const api=async(url,options={})=>{if(demo){if(options.method)throw new Error("A prévia local não publica alterações.");const parsed=new URL(url,location.origin);const slug=parsed.searchParams.get("slug");return slug?{game:await fetch(`/data/games/${slug}.json`).then(r=>r.json())}:{games:(await fetch("/data/index.json").then(r=>r.json())).games}}const response=await fetch(url,{...options,headers:{...(token?{authorization:`Bearer ${token}`}:{ }),...(options.body?{"content-type":"application/json"}:{}),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Não foi possível concluir a operação.");return data};
const t=(game,locale)=>game.translations?.[locale]||{};

async function boot(){if(demo){await openDashboard();return}config=await fetch("/api/admin/config").then(r=>r.json());if(token){try{await openDashboard();return}catch{sessionStorage.removeItem("67codes_admin_token");token=""}}authView.hidden=false}
loginForm.addEventListener("submit",async event=>{event.preventDefault();const message=$("#login-message");setMessage(message,"Entrando...");if(!config.configured)return setMessage(message,"O painel ainda precisa das variáveis de ambiente na Vercel.","error");try{const response=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${encodeURIComponent(config.firebaseApiKey)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:$("#login-email").value,password:$("#login-password").value,returnSecureToken:true})});const data=await response.json();if(!response.ok)throw new Error("E-mail ou senha inválidos.");token=data.idToken;sessionStorage.setItem("67codes_admin_token",token);await openDashboard()}catch(error){setMessage(message,error.message,"error")}});
async function openDashboard(){const data=await api("/api/admin/games");games=data.games;authView.hidden=true;dashboard.hidden=false;$("#admin-email").textContent=demo?"Prévia local":($("#login-email").value||"Administrador");renderGames()}
$("#logout").addEventListener("click",()=>{sessionStorage.removeItem("67codes_admin_token");location.reload()});
$("#game-search").addEventListener("input",renderGames);
function renderGames(){const query=$("#game-search").value.trim().toLowerCase();$("#game-list").replaceChildren(...games.filter(game=>t(game,"pt-BR").title.toLowerCase().includes(query)||game.slug.includes(query)).map(game=>{const button=document.createElement("button");button.type="button";button.className=`game-item ${game.slug===currentSlug?"active":""}`;button.innerHTML=`<img src="${game.icon}" alt=""><span><strong></strong><small></small></span>`;button.querySelector("strong").textContent=t(game,"pt-BR").title;button.querySelector("small").textContent=game.codeStatus==="no-code-system"?"Sem sistema de códigos":"Publicado";button.addEventListener("click",()=>loadGame(game.slug));return button}))}
async function loadGame(slug){setMessage($("#editor-message"),"");const {game}=await api(`/api/admin/games?slug=${encodeURIComponent(slug)}`);currentSlug=slug;fillForm(game);renderGames()}
function field(name){return gameForm.elements.namedItem(name)}
function fillForm(game){loadedGame=game;empty.hidden=true;gameForm.hidden=false;$("#editor-mode").textContent="EDITAR JOGO";$("#editor-heading").textContent=t(game,"pt-BR").title;field("slug").value=game.slug;field("slug").readOnly=true;field("robloxUrl").value=game.robloxUrl;field("titlePt").value=t(game,"pt-BR").title;field("titleEn").value=t(game,"en").title;field("descriptionPt").value=t(game,"pt-BR").description;field("descriptionEn").value=t(game,"en").description;field("tipsPt").value=(t(game,"pt-BR").tips||[]).join("\n");field("tipsEn").value=(t(game,"en").tips||[]).join("\n");for(const [suffix,locale] of [["Pt","pt-BR"],["En","en"]]){const redeem=t(game,locale).tutorials?.redeem||{};field(`tutorialTitle${suffix}`).value=redeem.title||"";field(`tutorialDescription${suffix}`).value=redeem.description||"";field(`steps${suffix}`).value=(redeem.steps||[]).join("\n")}field("codeStatus").value=game.codeStatus;field("codes").value=(game.codes||[]).join(", ");field("syncIcon").checked=game.assetSync?.icon!==false;field("syncThumbnail").checked=game.assetSync?.thumbnail===true;field("redeemTutorial").value=game.assets?.redeemTutorial||""}
$("#new-game").addEventListener("click",()=>{currentSlug="";loadedGame=null;gameForm.reset();empty.hidden=true;gameForm.hidden=false;field("slug").readOnly=false;field("syncIcon").checked=true;field("syncThumbnail").checked=true;$("#editor-mode").textContent="NOVO JOGO";$("#editor-heading").textContent="Novo cadastro";setMessage($("#editor-message"),"");renderGames()});
$$('.tab').forEach(button=>button.addEventListener("click",()=>{$$(".tab,.tab-panel").forEach(item=>item.classList.remove("active"));button.classList.add("active");$(`[data-panel="${button.dataset.tab}"]`).classList.add("active")}));
function formGame(){const slug=field("slug").value.trim(),noCodes=field("codeStatus").value==="no-code-system";const buildLocale=(suffix,locale)=>{const title=field(`title${suffix}`).value.trim(),pt=locale==="pt-BR";return {title,description:field(`description${suffix}`).value.trim(),tips:lines(field(`tips${suffix}`).value),tutorials:{redeem:{title:field(`tutorialTitle${suffix}`).value.trim()||(pt?`Como resgatar códigos em ${title}`:`How to redeem codes in ${title}`),description:field(`tutorialDescription${suffix}`).value.trim()||(noCodes?(pt?`${title} ainda não possui um sistema de códigos.`:`${title} does not have a code system yet.`):(pt?`Siga estas etapas para resgatar códigos ativos de ${title}.`:`Follow these steps to redeem active ${title} codes.`)),steps:lines(field(`steps${suffix}`).value),imageAlt:pt?`Tutorial de códigos de ${title}`:`${title} code redemption tutorial`}}}};return {slug,robloxUrl:field("robloxUrl").value.trim(),assets:{icon:`/assets/games/${slug}/icon.webp`,banner:loadedGame?.assets?.banner||"",thumbnail:`/assets/games/${slug}/thumbnail.webp`,redeemTutorial:field("redeemTutorial").value.trim()},assetSync:{icon:field("syncIcon").checked,thumbnail:field("syncThumbnail").checked},codeStatus:field("codeStatus").value,codes:codes(field("codes").value),translations:{en:buildLocale("En","en"),"pt-BR":buildLocale("Pt","pt-BR")}}}
$("#preview-json").addEventListener("click",()=>{$("#review-content").textContent=JSON.stringify(formGame(),null,2);$("#review-dialog").showModal()});
gameForm.addEventListener("submit",async event=>{event.preventDefault();const message=$("#editor-message"),button=$("#publish-game");setMessage(message,"Enviando para validação...");button.disabled=true;try{const result=await api("/api/admin/publish",{method:"POST",body:JSON.stringify({action:"upsert",game:formGame()})});setMessage(message,`${result.message} Identificador: ${result.requestId.slice(0,8)}`,"success")}catch(error){setMessage(message,error.message,"error")}finally{button.disabled=false}});
$("#archive-game").addEventListener("click",async()=>{if(!currentSlug)return setMessage($("#editor-message"),"Um cadastro ainda não publicado não pode ser arquivado.","error");if(!confirm("Arquivar este jogo? A página deixará de aparecer no site, mas os dados serão preservados."))return;try{const result=await api("/api/admin/publish",{method:"POST",body:JSON.stringify({action:"archive",slug:currentSlug})});setMessage($("#editor-message"),result.message,"success")}catch(error){setMessage($("#editor-message"),error.message,"error")}});
boot().catch(()=>setMessage($("#login-message"),"Não foi possível carregar o painel.","error"));
